apiVersion: v1
kind: Service
metadata:
  name: ms-pedidos-service
spec:
  selector:
    app: ms-pedidos
  ports:
    - protocol: TCP
      port: 8082        # puerto del Service dentro del cluster
      targetPort: 8082  # puerto del contenedor
  type: LoadBalancer    # expone externamente
