# Puerto del microservicio de pedidos
server.port=8082

# Nombre de la aplicación
spring.application.name=ms-pedidos

# Configuración de PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/db_pedidos
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Inicializar schema
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# URL del ms-productos (comunicación entre microservicios)
ms.productos.url=http://localhost:8081/api/productos
